title:              "밍통방통"
tagline:            "坚持到底就是胜利"
email:              "kimminji971031@gmail.com"
description:        "세상에 다양한 트렌드를 공유하는 블로그"
author:             "김민지"
baseurl:            "/"
url:                "https://mingluv.github.io"
locale:             "ko_KR"
thumbnail:          "img/bg-index.jpg"

# Social Profiles
twitter_username:   miing_luv
instagram_username: mingluv_daily
linkedin_username:  in/mingluv/

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
