title:              "Cloud Trend"
tagline:            "몽글몽글 구름 한 점 가져가세요"
email:              "kimminji971031@gmail.com"
description:        "세상에 다양한 트렌드를 공유하는 블로그"
author:             "김민지"
baseurl:            "/"
url:                "https://mingluv.github.io"
locale:             "ko_KR"
thumbnail:          "img/bg-index.jpg"

# Social Profiles
twitter_username:   miing_luv
instagram_username: mingluv_daily
linkedin_username:  mingluv

# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

# 블로그 disqus shortname
disqus:
  shortname: mingluv
